addSbtPlugin("com.dwijnand"     % "sbt-dynver"           % "4.0.0")
addSbtPlugin("com.geirsson"     % "sbt-scalafmt"         % "1.5.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.5.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.12")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"      % "2.4.9")
