// addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.5.2")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"          % "1.4.0")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"           % "0.3.3")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph"  % "0.9.0")
addSbtPlugin("com.dwijnand"       % "sbt-dynver"            % "2.0.0")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"       % "2.2.1")
